import React,{useEffect,useMemo,useState} from 'react';
import { ASSESSMENT_QUESTIONS } from '../assessmentModel';
import { useLanguage } from '../i18n/LanguageContext';
import LanguageToggle from './LanguageToggle';
import { getAlphaSession,submitAlphaAssessment,submitAlphaFeedback } from '../services/alphaService';
import type { AlphaResult,AlphaSession } from '../alpha/types';

const options=[1,2,3,4,5] as const;
const labels={en:['Not true','A little','Somewhat','Mostly','Very true'],ru:['Совсем не верно','Скорее нет','Отчасти','В основном','Полностью верно']};
const factorNames={workloadBalance:{en:'Workload balance',ru:'Баланс нагрузки'},recovery:{en:'Recovery',ru:'Восстановление'},controlClarity:{en:'Control & clarity',ru:'Контроль и ясность'}};
const statusNames={green:{en:'Green',ru:'Устойчиво'},stable:{en:'Stable',ru:'Стабильно'},needs_attention:{en:'Needs attention',ru:'Требует внимания'},at_risk:{en:'At risk',ru:'Зона риска'}};

const Card:React.FC<React.PropsWithChildren<{className?:string}>>=({children,className=''})=><div className={'bg-white border border-slate-200 rounded-[1.75rem] shadow-sm p-5 sm:p-7 '+className}>{children}</div>;

const AlphaView:React.FC=()=>{
 const {language,t}=useLanguage();
 const token=useMemo(()=>decodeURIComponent(window.location.hash.slice(1)),[]);
 const [session,setSession]=useState<AlphaSession|null>(null);
 const [result,setResult]=useState<AlphaResult|null>(null);
 const [answers,setAnswers]=useState<Record<string,number>>({});
 const [step,setStep]=useState(0); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
 const [feedback,setFeedback]=useState(false);
 const load=async()=>{if(!token){setSession({valid:false});return;} setBusy(true);setError('');try{const s=await getAlphaSession(token,language);setSession(s);setResult(s.result||null);setFeedback(Boolean(s.feedbackSubmitted));}catch{setError(t('Service is temporarily unavailable.','Сервис временно недоступен.'));}finally{setBusy(false);}};
 useEffect(()=>{void load();},[language]);
 const questions=ASSESSMENT_QUESTIONS.slice(step*3,step*3+3);
 const next=async()=>{if(questions.some(q=>!answers[String(q.id)])){setError(t('Please answer all three questions.','Ответьте на все три вопроса.'));return;}setError('');if(step<3){setStep(step+1);window.scrollTo(0,0);return;}setBusy(true);try{const r=await submitAlphaAssessment(token,answers,language);setResult(r.result);setSession(s=>s?{...s,baselineSubmitted:true,result:r.result}:s);window.scrollTo(0,0);}catch{setError(t('Could not save your assessment. Your answers are preserved — please retry.','Не удалось сохранить оценку. Ответы сохранены — попробуйте ещё раз.'));}finally{setBusy(false);}};
 const sendFeedback=async(rating:number)=>{setBusy(true);try{await submitAlphaFeedback(token,rating);setFeedback(true);}catch{setError(t('Could not save feedback. Please retry.','Не удалось сохранить отзыв. Попробуйте ещё раз.'));}finally{setBusy(false);}};
 if(!session&&!error)return <Shell><Card>{t('Loading your private assessment…','Загружаем вашу приватную оценку…')}</Card></Shell>;
 if(error&&!session)return <Shell><Card><h1 className="text-xl font-bold mb-2">{t('Temporarily unavailable','Временно недоступно')}</h1><p className="text-slate-600 mb-4">{error}</p><button onClick={load} className="px-4 py-2 rounded-xl bg-indigo-600 text-white">{t('Retry','Повторить')}</button></Card></Shell>;
 if(!session?.valid)return <Shell><Card><h1 className="text-xl font-bold mb-2">{t('This invite is invalid or expired','Эта ссылка недействительна или устарела')}</h1><p className="text-slate-600">{t('Ask the study coordinator for a new private link.','Попросите координатора исследования прислать новую приватную ссылку.')}</p></Card></Shell>;
 if(result)return <Shell><Card><p className="text-xs font-semibold uppercase tracking-wider text-indigo-600 mb-2">{session.department?.displayName}</p><h1 className="text-3xl font-bold">{result.score}/100</h1><p className="text-slate-600 mt-1">{statusNames[result.status][language]}</p><div className="grid sm:grid-cols-3 gap-3 mt-6">{Object.entries(result.factors).map(([key,v])=><div key={key} className="rounded-2xl bg-slate-50 p-4"><p className="text-sm font-semibold">{factorNames[key as keyof typeof factorNames][language]}</p><p className="text-2xl font-bold mt-1">{v.score}</p></div>)}</div><div className="mt-6 rounded-2xl bg-indigo-50 p-4"><p className="font-semibold">{t('What stands out','Что выделяется')}</p><p className="text-slate-700 mt-1">{result.insight}</p></div><div className="mt-6 space-y-3">{[result.actions.today,result.actions.week,result.actions.support].map(a=><div key={a.id} className="border border-slate-200 rounded-2xl p-4"><p className="font-semibold">{a.title}</p><p className="text-slate-600 mt-1">{a.body}</p></div>)}</div><div className="mt-7 border-t border-slate-200 pt-5">{feedback?<p className="font-semibold">{t('Thank you — feedback saved.','Спасибо — отзыв сохранён.')}</p>:<><p className="font-semibold mb-3">{t('Were these recommendations useful?','Эти рекомендации были полезны?')}</p><div className="flex gap-2">{[1,2,3,4,5].map(n=><button disabled={busy} key={n} onClick={()=>sendFeedback(n)} className="w-10 h-10 rounded-xl border border-slate-300 hover:bg-slate-50">{n}</button>)}</div></>}</div>{error&&<p className="text-sm text-rose-600 mt-4">{error}</p>}</Card></Shell>;
 return <Shell><Card><div className="flex justify-between gap-4 items-start"><div><p className="text-xs font-semibold uppercase tracking-wider text-indigo-600">{session.department?.displayName}</p><h1 className="text-2xl font-bold mt-1">{t('Work sustainability check-in','Оценка устойчивости работы')}</h1><p className="text-slate-600 mt-2">{t('Thinking about the past 2 weeks, how true has each statement been for you?','Вспоминая последние 2 недели, насколько каждое утверждение было верно для вас?')}</p></div><span className="text-sm text-slate-500 whitespace-nowrap">{step+1}/4</span></div><div className="mt-7 space-y-7">{questions.map(q=><div key={q.id}><p className="font-medium">{q.id}. {language==='ru'?q.ru:q.en}</p><div className="grid grid-cols-5 gap-2 mt-3">{options.map((n,i)=><button key={n} onClick={()=>{setAnswers(a=>({...a,[String(q.id)]:n}));setError('');}} className={'min-h-14 rounded-xl border text-xs sm:text-sm px-1 '+(answers[String(q.id)]===n?'bg-indigo-600 text-white border-indigo-600':'bg-white border-slate-300 hover:bg-slate-50')}><span className="block font-bold">{n}</span><span className="hidden sm:block mt-1">{labels[language][i]}</span></button>)}</div></div>)}</div>{error&&<p className="text-sm text-rose-600 mt-5">{error}</p>}<div className="flex justify-between mt-7"><button disabled={step===0||busy} onClick={()=>setStep(s=>s-1)} className="px-4 py-2 rounded-xl border border-slate-300 disabled:opacity-30">{t('Back','Назад')}</button><button disabled={busy} onClick={next} className="px-5 py-2 rounded-xl bg-indigo-600 text-white disabled:opacity-50">{busy?t('Saving…','Сохраняем…'):step===3?t('See my result','Показать результат'):t('Continue','Продолжить')}</button></div></Card></Shell>;
};
const Shell:React.FC<React.PropsWithChildren>=({children})=>{const {t}=useLanguage();return <main className="min-h-screen bg-slate-50 text-slate-900 p-4 sm:p-8"><div className="max-w-3xl mx-auto"><header className="flex items-center justify-between mb-5"><div><p className="font-bold">Resilience</p><p className="text-xs text-slate-500">{t('Anonymous internal alpha','Анонимная внутренняя альфа')}</p></div><LanguageToggle compact/></header>{children}<p className="text-xs text-slate-500 text-center mt-4">{t('Your individual answers are not shown to your manager.','Ваши индивидуальные ответы не показываются руководителю.')}</p></div></main>};
export default AlphaView;